version: 2.1
orbs:
  unity: game-ci/unity@1.0.0
workflows:
  test-build-with-executors:
    jobs:
      - unity/test:
          context: unity
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            editor_version: 2021.3.3f1
            name: unity/ubuntu
            resource_class: medium
            target_platform: mac-mono
          name: test-macOS
          step-name: Run tests on macOS
          test-platform: playmode
          