version: 2.1
orbs:
  unity: game-ci/unity@1.0.0
workflows:
  test-build-with-executors:
    jobs:
      - unity/test:
          context: unity-orb
          executor:
            editor_version: 2021.3.1f1
            name: unity/ubuntu
            resource_class: medium
            target_platform: linux-il2cpp
          name: test-linux
          project-path: Unity2D-Demo-Game-CI-CD/src
          step-name: Run tests on Linux
          test-platform: playmode
          unity-license-var-name: UNITY_ENCODED_LICENSE