version: 2.1
orbs:
  unity: game-ci/unity@1.0.0
workflows:
  create-unity-activation-file:
    jobs:
      - unity/create-activation-file: 
          editor_version: 2021.3.3f1
  test-build-with-executors:
    jobs:
      - unity/build:
          context: unity
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-username-var-name: UNITY_USERNAME
          unity-password-var-name: UNITY_PASSWORD
          executor:
            editor_version: 2021.3.3f1
            name: unity/ubuntu
            resource_class: medium
            target_platform: mac-mono
          name: test-macOS
          step-name: Run tests on macOS
          build-target: StandaloneOSX
          