version: 2.1
orbs:
  unity: game-ci/unity@1.0.0
workflows:
  # create-unity-activation-file:
  #   jobs:
  #     - unity/create-activation-file: 
  #         editor_version: 2021.3.3f1
  test-build-with-executors:
    jobs:
      - unity/test:
          context: unity
          executor:
            editor_version: 2021.3.3f1
            name: unity/ubuntu
            resource_class: medium
            target_platform: linux-il2cpp
          name: test-linux
          step-name: Run tests on Linux
          test-platform: playmode
          # unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-serial-var-name: UNITY_SERIAL
          unity-password-var-name: UNITY_PASSWORD
          unity-username-var-name: UNITY_USERNAME
      - unity/test:
          context: unity
          executor:
            editor_version: 2021.3.3f1
            name: unity/windows-2019
            size: large
            target_platform: windows-il2cpp
          name: test-windows
          step-name: Run tests on Windows
          test-platform: playmode
          unity-password-var-name: UNITY_PASSWORD
          unity-serial-var-name: UNITY_SERIAL
          unity-username-var-name: UNITY_USERNAME
      - unity/build:
          build-target: Android
          context: unity
          executor:
            editor_version: 2021.3.3f1
            name: unity/ubuntu
            resource_class: large
            target_platform: android
          name: build-android
          requires:
            - test-linux
          step-name: Build Android
          unity-password-var-name: UNITY_PASSWORD
          unity-serial-var-name: UNITY_SERIAL
          unity-username-var-name: UNITY_USERNAME
      - unity/build:
          build-target: iOS
          context: unity
          executor:
            editor_version: 2021.3.3f1
            name: unity/ubuntu
            resource_class: large
            target_platform: ios
          name: build-ios
          requires:
            - test-linux
          step-name: Build iOS
          unity-password-var-name: UNITY_PASSWORD
          unity-serial-var-name: UNITY_SERIAL
          unity-username-var-name: UNITY_USERNAME
    